const genericArticleSelectors = [
  "[itemprop='articleBody']",
  ".entry-content",
  ".post-content",
  ".article-content",
  ".article-body",
  ".story-body",
  ".story-content",
  ".news-article-content",
  ".field--name-body",
  "article .content",
  "article",
  "main article",
  "main",
];

function wordpress(id, name, homeUrl, apiBase, options = {}) {
  return {
    id,
    name,
    homeUrl,
    strategy: "wordpress",
    apiBase,
    articleSelectors: genericArticleSelectors,
    ...options,
  };
}

export const SOURCES = [
  wordpress("ffxnow", "FFXnow", "https://www.ffxnow.com/", "https://www.ffxnow.com/wp-json/wp/v2/posts", {
    tags: [9],
    optionalScope: true,
  }),
  {
    id: "gazetteleader",
    name: "GazetteLeader / Sun Gazette successor",
    homeUrl: "https://gazetteleader.com/",
    strategy: "wayback",
    archiveHost: "gazetteleader.com",
    archiveUrlPattern: "gazetteleader.com/all-news/*",
    delayMs: 1_500,
    smokeRange: { start: "2024-01-01T00:00:00Z", endExclusive: "2024-12-01T00:00:00Z" },
    articleSelectors: genericArticleSelectors,
  },
  {
    id: "connection-newspapers",
    name: "Connection Newspapers",
    homeUrl: "https://www.connectionnewspapers.com/",
    strategy: "sitemap",
    sitemapUrl: "https://www.connectionnewspapers.com/sitemap.xml",
    sitemapMatch: /sitemap-news-story\.xml/i,
    articleMatch: /^https:\/\/www\.connectionnewspapers\.com\/news\/\d{4}\/[a-z]{3}\/\d{1,2}\/[^/]+\/?$/i,
    urlDatePattern: /\/news\/(\d{4})\/([a-z]{3})\/(\d{1,2})\//i,
    articleSelectors: [".story-body", ".article-body", ".content-body", ...genericArticleSelectors],
  },
  wordpress(
    "falls-church-news-press",
    "Falls Church News-Press",
    "https://www.fcnp.com/",
    "https://www.fcnp.com/wp-json/wp/v2/posts",
    { tags: [18463], optionalScope: true, delayMs: 10_000 },
  ),
  {
    id: "falls-church-independent",
    name: "Falls Church Independent",
    homeUrl: "https://www.fallschurchindependent.com/",
    strategy: "ghost",
    apiBase: "https://www.fallschurchindependent.com/ghost/api/content/posts/",
    articleSelectors: [".gh-content", ".post-content", ...genericArticleSelectors],
  },
  {
    id: "tysons-corner-patch",
    name: "Tysons Corner Patch",
    homeUrl: "https://patch.com/virginia/tysonscorner",
    strategy: "patch-next",
    listingUrl: "https://patch.com/virginia/tysonscorner?page={page}",
    localAlias: "/virginia/tysonscorner",
    articleSelectors: [".article-body", ".article-content", "[data-testid='article-content']", ...genericArticleSelectors],
  },
  wordpress("tysonstoday", "TysonsToday", "https://tysonstoday.com/", "https://tysonstoday.com/wp-json/wp/v2/posts", {
    fallbackFeedUrl: "https://tysonstoday.com/feed/",
  }),
  wordpress(
    "wtop-fairfax-county",
    "WTOP Fairfax County",
    "https://wtop.com/local/virginia/fairfax-county/",
    "https://wtop.com/wp-json/wp/v2/posts",
    {
      categories: [210356],
      articleSelectors: [".article-content", ".story-content", ...genericArticleSelectors],
    },
  ),
  {
    id: "fairfax-county-newscenter",
    name: "Fairfax County NewsCenter",
    homeUrl: "https://www.fairfaxcounty.gov/news/",
    strategy: "monthly-html",
    monthUrl: "https://www.fairfaxcounty.gov/news/monthly/{yyyymm}",
    listingSelector: ".view-content",
    articleMatch: /^https:\/\/www\.fairfaxcounty\.gov\/news\/(?!monthly|newswire)[^/?#]+$/i,
    articleSelectors: [".field--name-body", ".node__content", ...genericArticleSelectors],
  },
  {
    id: "providence-district-newsletter",
    name: "Providence District Newsletter / The Palchik Post",
    homeUrl: "https://palchik-post.beehiiv.com/",
    strategy: "sitemap",
    sitemapUrl: "https://palchik-post.beehiiv.com/sitemap.xml",
    articleMatch: /^https:\/\/palchik-post\.beehiiv\.com\/p\/[^/?#]+\/?$/i,
    articleSelectors: [".post-content", "[data-testid='post-content']", ...genericArticleSelectors],
  },
  {
    id: "fairfax-county-tysons-portal",
    name: "Fairfax County Tysons Portal",
    homeUrl: "https://www.fairfaxcounty.gov/tysons/",
    strategy: "reference-pages",
    referenceUrls: [
      "https://www.fairfaxcounty.gov/tysons/",
      "https://www.fairfaxcounty.gov/tysons/annual-report",
      "https://www.fairfaxcounty.gov/tysons/development-activity",
      "https://www.fairfaxcounty.gov/tysons/comprehensive-plan",
      "https://www.fairfaxcounty.gov/tysons/reports-studies",
      "https://www.fairfaxcounty.gov/tysons/tysons-plan-timeline",
    ],
    articleSelectors: [".field--name-body", "main", ...genericArticleSelectors],
    recordType: "reference-page",
  },
  wordpress(
    "fcpd-tysons-urban-team",
    "FCPD News — Tysons Urban Team",
    "https://fcpdnews.org/news/?fcpd_cat=tysons-urban-team",
    "https://fcpdnews.org/wp-json/wp/v2/posts",
    { categories: [425881758] },
  ),
  wordpress(
    "fairfax-county-fire-rescue-news",
    "Fairfax County Fire and Rescue News",
    "https://ffxfirerescue.wordpress.com/",
    "https://public-api.wordpress.com/wp/v2/sites/ffxfirerescue.wordpress.com/posts",
  ),
  {
    id: "fairfax-county-transportation-news",
    name: "Fairfax County Transportation News",
    homeUrl: "https://www.fairfaxcounty.gov/transportation/news",
    strategy: "single-index",
    indexUrl: "https://www.fairfaxcounty.gov/transportation/news",
    listingSelector: ".widget.accordion",
    cardSelector: "li",
    useLastListingDate: true,
    requireListingDate: true,
    articleMatch: /^https:\/\/www\.fairfaxcounty\.gov\/(?:transportation\/)?news\/[Tt][^/?#]+$/i,
    articleSelectors: [".field--name-body", ".node__content", ...genericArticleSelectors],
  },
  {
    id: "wmata-news",
    name: "WMATA News",
    homeUrl: "https://www.wmata.com/news.html",
    strategy: "wmata",
    apiUrl:
      "https://www.wmata.com/news/_jcr_content/root/container/row-container/main-container/main-editable/news_listing.results.json",
    articleSelectors: [".news-release", ".cmp-text", ".article-body", ...genericArticleSelectors],
  },
  {
    id: "town-of-vienna-newsroom",
    name: "Town of Vienna Newsroom",
    homeUrl: "https://www.viennava.gov/Newsroom/Town-Publications/News-Releases",
    strategy: "rendered-pdf-links",
    linkMatch: /^https:\/\/www\.viennava\.gov\/files\/[^/]+\/.+\.pdf(?:\?.*)?$/i,
    browserOnly: true,
    recordType: "press-release",
  },
  {
    id: "city-of-falls-church-news-releases",
    name: "City of Falls Church News Releases",
    homeUrl: "https://www.fallschurchva.gov/250/Communications-Public-Information",
    strategy: "rss",
    feedUrl:
      "https://us4.campaign-archive.com/feed?u=6285c81a1416df81ae70592b9&id=4bb1b3d647",
    articleSelectors: [".mcnTextContent", ".bodyContainer", ...genericArticleSelectors],
  },
  {
    id: "fcps-news",
    name: "FCPS News",
    homeUrl: "https://www.fcps.edu/news",
    strategy: "paginated-html",
    listingUrl: "https://www.fcps.edu/news?page={page}",
    startPage: 0,
    articleMatch: /^https:\/\/www\.fcps\.edu\/news\/[^/?#]+$/i,
    articleSelectors: [".field--name-body", ".node__content", ...genericArticleSelectors],
  },
  {
    id: "fairfax-county-school-board",
    name: "Fairfax County School Board",
    homeUrl: "https://www.fcps.edu/about-fcps/leadership/school-board",
    strategy: "fcps-board",
    listingUrl: "https://www.fcps.edu/news?page={page}",
    startPage: 0,
    articleMatch: /^https:\/\/www\.fcps\.edu\/news\/[^/?#]+$/i,
    articleSelectors: [".field--name-body", ".node__content", ...genericArticleSelectors],
    recordFilter: /\bschool board\b|\bboard meeting\b|\bboard member\b/i,
  },
  wordpress(
    "tysons-community-alliance-news",
    "Tysons Community Alliance News",
    "https://tysonsva.org/news/",
    "https://tysonsva.org/wp-json/wp/v2/posts",
    { categories: [3, 13], forceOrigin: "https://tysonsva.org" },
  ),
  wordpress(
    "mclean-community-center-news",
    "McLean Community Center News",
    "https://mcleancenter.org/about/news/",
    "https://mcleancenter.org/wp-json/wp/v2/posts",
    { categories: [1, 20] },
  ),
  {
    id: "fairfax-county-public-library-news-events",
    name: "Fairfax County Public Library News and Events",
    homeUrl: "https://www.fairfaxcounty.gov/library/news-and-events",
    strategy: "paginated-html",
    listingUrl: "https://www.fairfaxcounty.gov/library/news-and-events?news-and-events=&page={page}",
    startPage: 0,
    listingSelector: ".view-content",
    cardSelector: ".row",
    articleMatch: /^https:\/\/www\.fairfaxcounty\.gov\/library\/(?:news\/)?[^/?#]+$/i,
    articleSelectors: [".field--name-body", ".node__content", ...genericArticleSelectors],
  },
  {
    id: "the-highlander-mclean-high-school",
    name: "The Highlander — McLean High School",
    homeUrl: "https://thehighlandernews.com/",
    strategy: "sitemap",
    sitemapUrl: "https://thehighlandernews.com/wp-sitemap.xml",
    sitemapMatch: /wp-sitemap-posts-post-\d+\.xml/i,
    globalSitemapSort: true,
    filterByLastmod: true,
    articleMatch: /^https:\/\/thehighlandernews\.com\/\d+\/[^/]+\/[^/]+\/?$/i,
    articleSelectors: [".sno-story-body-content", ".storycontent", ".entry-content", ...genericArticleSelectors],
    delayMs: 6_000,
  },
  {
    id: "the-saxon-scope-langley-high-school",
    name: "The Saxon Scope — Langley High School",
    homeUrl: "https://www.saxonscope.com/",
    strategy: "sitemap",
    sitemapUrl: "https://www.saxonscope.com/wp-sitemap.xml",
    sitemapMatch: /wp-sitemap-posts-post-\d+\.xml/i,
    globalSitemapSort: true,
    articleMatch: /^https:\/\/www\.saxonscope\.com\/[^/]+\/\d{4}\/\d{2}\/\d{2}\/[^/]+\/?$/i,
    urlDatePattern: /\/(\d{4})\/(\d{2})\/(\d{2})\//,
    articleSelectors: [".sno-story-body-content", ".storycontent", ".entry-content", ...genericArticleSelectors],
    delayMs: 6_000,
  },
  {
    id: "rank-and-file-marshall-high-school",
    name: "Rank & File — Marshall High School",
    homeUrl: "https://www.gcmnews.net/",
    strategy: "wayback",
    archiveHost: "gcmnews.net",
    archiveUrlByPublicationYear: "gcmnews.net/{year}/*",
    delayMs: 1_500,
    smokeRange: { start: "2010-01-01T00:00:00Z", endExclusive: "2011-01-01T00:00:00Z" },
    articleSelectors: [".sno-story-body-content", ".storycontent", ".entry-content", ...genericArticleSelectors],
  },
];

export const SOURCE_BY_ID = new Map(SOURCES.map((source) => [source.id, source]));

export function getSource(id) {
  const source = SOURCE_BY_ID.get(id);
  if (!source) {
    throw new Error("Unknown source '" + id + "'. Run npm run scrape:list to see available sources.");
  }
  return source;
}
